# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SolidariGee Watanopie-Kampagne
author: SolidariGee e.V.
email: info@solidarigee.de
description: > # this means to ignore newlines until "baseurl:"
  Mit der Kampagne ›#watanopie – Heimat, ein Ort der Utopie?‹ sprechen junge Berliner erstmalig
  von einer ›Utopie der Heimat‹ und treten ein für Dialog und gesellschaftliche Partizipation.
# baseurl: ""
# url: ""
# baseurl: "/solidarigee-kunstevent" # the subpath of your site, e.g. /blog
# url: "http://max.jendruk.com/solidarigee-kunstevent" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/watanopie_4868e9f1" # the subpath of your site, e.g. /blog
url: "http://www.solidarigee.de" # the base hostname & protocol for your site, e.g. http://example.com
lang: de-DE

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: authors_profile
      sold: false

autoprefixer:
  only_production: true

hyphenate_filter:
  language: de
  left: 4
  right: 3
  # hyphen: "&shy;"

gems:
  - jekyll-autoprefixer

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - watanopie.sublime-project
  - watanopie.sublime-workspace
  - ToDo.md
  - Zugang.jpg
  - mockup.psd
